apiVersion: apps/v1
kind: Deployment
metadata:
  name: hothash-worker
spec:
  replicas: 20
  selector:
    matchLabels:
      app: hothash-worker
  template:
    metadata:
      labels:
        app: hothash-worker
    spec:
      containers:
        - name: hothash-worker
          image: asia-east2-docker.pkg.dev/dbgroup/hothash/worker:latest
          resources:
            requests:
              memory: "32Gi"
              cpu: "4"
            limits:
              memory: "32Gi"
              cpu: "4"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: gcs-key
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: gcs-key
          secret:
            secretName: gcp-sa-key
